CREATE TABLE IF NOT EXISTS users (
    id INTEGER NOT NULL PRIMARY KEY,
    username VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS games (
    id INTEGER NOT NULL PRIMARY KEY,
    started BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS game_users (
    game INTEGER NOT NULL,
    user INTEGER NOT NULL,
    PRIMARY KEY (game, user),
    FOREIGN KEY (game) REFERENCES games (id) ON DELETE CASCADE,
    FOREIGN KEY (user) REFERENCES users (id) ON DELETE CASCADE
);
